### ISSUE TITLE
Audiosplitter not working

### ISSUE THREAD

**Issue by Skizzie** [JarodMica/audiosplitter#1]
`audiosplitter.py:95: WavFileWarning: Chunk (non-data) not understood, skipping it.
Traceback (most recent call last):
  File "audiosplitter.py", line 213, in <module>
  File "audiosplitter.py", line 97, in run_audioseg
  File "numpy\core\getlimits.py", line 677, in __init__
ValueError: Invalid integer data type 'f'.
[12236] Failed to execute script 'audiosplitter' due to unhandled exception!`

Whenever I use the option 1 i get this error, i made sure the input file is ".wav"

**Comment by JarodMica** [comment]
Make sure that the .wav file was natively a .wav file and not just renamed with the .wav extension.  You might wanna remux it or re-encode it to wav and see if this gets rid of the issue as the error indicates and issue when trying to read the input file.

**Comment by Skizzie** [comment]
Okay, that seemed to be the case, I used Adobe Audition to save the mp3 file as wav, and that didn't seem to work, but when it's properly re-encoded everything works just fine.
